# Generated by Django 3.2.15 on 2022-09-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='games_counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.PositiveIntegerField()),
                ('pc', models.PositiveIntegerField()),
            ],
        ),
    ]
