apiVersion: v1

kind: Service

metadata:
  name: evenodds-lb
  namespace: evenodds-ns

spec:
  type: LoadBalancer
  selector: 
      app: evenodds-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000