apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: evenodds-hpa
  namespace: evenodds-ns
spec:
  maxReplicas: 5
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: evenodds-deployment
  targetCPUUtilizationPercentage: 70