apiVersion: v1
kind: Secret
metadata:
  name: evenodds-db-secret
  namespace: evenodds-ns
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXM=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
