apiVersion: v1
kind: Service
metadata:
  name: evenodds-app-ddbb-connect
  namespace: evenodds-ns
spec:
  type: ClusterIP
  selector:
    app: evenodds-stateful
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
