apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "evenodds.fullname" . }}-app-cfgmp
  namespace: {{ .Values.namespace }}
data:
  # property-like keys; each key maps to a simple value
  APP_PORT: "9000"
  MAX_LOGS_SIZE: {{ .Values.cfApp.maxLogsSize | quote }}
  MAX_LOGS_FILES: {{ .Values.cfApp.maxLogsFiles | quote }}
  POSTGRES_HOST: "db"
  
