apiVersion: v1
kind: Service
metadata:
  name: {{ include "evenodds.fullname" . }}-headless # tiene que hacer match con el statefulset 'serviceName'
  labels:
    {{- include "evenodds.selectorLabels" . | nindent 4 }} 
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None # Mana
  selector:
    app: evenodds-stateful # apunta a pods