apiVersion: v1
kind: Secret
metadata:
  name: {{ include "evenodds.fullname" . }}-db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.dbSecret.psDb | b64enc }}
  POSTGRES_USER: {{ .Values.dbSecret.psUser | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.dbSecret.psPass | b64enc }}
