apiVersion: v1

kind: Service

metadata:
  name: {{ include "evenodds.fullname" . }}-lb
  namespace: {{ .Values.namespace }}

spec:
  {{- if .Values.ingress }}
  type: ClusterIP
  {{- else }}
  type: LoadBalancer
  {{- end }}
  selector: 
      app: evenodds-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000