apiVersion: v1
kind: Service
metadata:
  name: {{ include "evenodds.fullname" . }}-app-ddbb-connect
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: evenodds-stateful
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
